export const CLAIM_EVIDENCE_TYPES=Object.freeze([
  "CASE_FILE",
  "PROBE_RESULT",
  "DIFFERENTIAL_SNAPSHOT",
  "CONFERENCE_REPORT",
  "BENCHMARK_REPORT",
  "EVALUATION_RECEIPT",
  "REPLICATION_RECEIPT",
  "REPLICATION_SUMMARY",
  "CLAIM_CHALLENGE_RESULT",
  "EXTERNAL_REFERENCE"
]);

export const CLAIM_EVIDENCE_RELATIONS=Object.freeze([
  "SUPPORTS",
  "CONTRADICTS",
  "QUALIFIES",
  "CONTEXT"
]);

export const CLAIM_STATUSES=Object.freeze([
  "UNASSESSED",
  "SUPPORT_ONLY",
  "CONTESTED",
  "CONTRADICTED",
  "SUPERSEDED"
]);

export const CLAIM_EVIDENCE_GRADES=Object.freeze([
  "NO_EVIDENCE",
  "PRELIMINARY_SUPPORT",
  "MULTI_SOURCE_SUPPORT",
  "REPLICATION_SUPPORT",
  "ROBUST_REPLICATION_CANDIDATE",
  "CONTESTED_EVIDENCE",
  "ADVERSE_EVIDENCE_ONLY"
]);
