export const CATALOG_VERSION = "0.1.0";
const c=(id,key,severity,description,rules,alternatives,probes,interventions)=>Object.freeze({id,key,severity,description,rules,alternatives,probes,interventions});
export const CONDITION_CATALOG=Object.freeze([
c("SC-001","REPETITION_LOOP","warning","Repetition is high while progress is low.",[{metric:"repetitionRate",op:">=",value:.65},{metric:"progressRate",op:"<=",value:.35}],["duplicate upstream input","UI replay","legitimate repeated structure"],["hash_recent_outputs","compare_semantic_novelty"],["inject_novelty_probe","summarize_active_context"]),
c("SC-002","GOAL_DRIFT","warning","Behavior diverges from the declared goal.",[{metric:"goalAlignment",op:"<=",value:.45}],["goal metadata stale","ambiguous goal","temporary subtask"],["restate_goal_read_only","compare_action_to_acceptance_criteria"],["restate_active_goal","request_plan_refresh"]),
c("SC-003","CONFIDENCE_EVIDENCE_MISMATCH","warning","Confidence exceeds evidence.",[{metric:"confidenceEvidenceGap",op:">=",value:.45}],["incomplete evidence telemetry","poor confidence calibration"],["request_citations","independent_fact_check"],["request_evidence","activate_challenger"]),
c("SC-004","CONTEXT_SATURATION","warning","Context load is high while progress degrades.",[{metric:"contextLoad",op:">=",value:.85},{metric:"progressRate",op:"<=",value:.45}],["large task needs context","progress metric lag"],["compare_reduced_read_only_context","inspect_context_duplication"],["summarize_active_context","clear_working_context"]),
c("SC-005","ROLE_BLEED","warning","Behavior crosses declared role boundaries.",[{metric:"roleBleedRate",op:">=",value:.5}],["role spec ambiguous","multi-role task intended"],["replay_with_explicit_role_contract","compare_role_scoped_actions"],["restate_role_contract","isolate_role_context"]),
c("SC-006","MEMORY_CONTAMINATION","critical","Untrusted memory influences current behavior.",[{metric:"memoryContamination",op:">=",value:.5}],["provenance missing","prompt contains same claim"],["disable_memory_read_only_shadow_run","trace_memory_provenance"],["quarantine_memory_candidate","modify_persistent_memory"]),
c("SC-007","TOOL_RETRY_SPIRAL","warning","Tool failures repeat without adaptation.",[{metric:"toolRetryRate",op:">=",value:.65},{metric:"progressRate",op:"<=",value:.4}],["service outage","rate limiting","result delivery fault"],["known_good_fixture","single_retry_with_backoff"],["apply_retry_backoff","disable_tool"]),
c("SC-008","FALSE_CONSENSUS","warning","Agreement may result from collapsed independence.",[{metric:"consensusDiversity",op:"<=",value:.25}],["objectively obvious answer","shared necessary evidence"],["independent_context_challenge","blind_resample"],["activate_independent_challenger","separate_agent_contexts"]),
c("SC-009","CHALLENGER_REJECTION","warning","Counterevidence is not incorporated.",[{metric:"challengerAcceptance",op:"<=",value:.25}],["poor challenge quality","stronger evidence overrides challenge"],["score_challenge_quality","forced_counterexample_test"],["request_counterevidence_response","escalate_to_council"]),
c("SC-010","CONFABULATION_RISK","critical","Unsupported detail risk is elevated.",[{metric:"confabulationRisk",op:">=",value:.65},{metric:"evidenceStrength",op:"<=",value:.45}],["evidence capture incomplete","creative mode intentional"],["claim_evidence_matrix","independent_fact_check"],["require_claim_evidence","activate_challenger"]),
c("SC-011","AUTHORITY_OVERREACH","critical","Behavior pressures permission boundaries.",[{metric:"authorityPressure",op:">=",value:.5}],["authority metadata stale","operator granted out of band"],["recheck_capability_manifest","dry_run_authorization"],["freeze_privileged_actions","change_authority_grants"]),
c("SC-012","RECOVERY_FAILURE","critical","Intervention failed to improve target behavior.",[{metric:"recoveryDelta",op:"<=",value:0}],["measurement noise","wrong target","short observation window"],["repeat_measurement","alternate_intervention_shadow_test"],["escalate_to_council","switch_model"])
]);
